apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: hello-liberty-cicd
spec:
  serviceAccountName: pipeline
  triggers:
    - name: hello-liberty-cicd-trigger
      binding:
        name: basic-binding-cicd
      template:
        name: hello-liberty-template-cicd